// Mock del JSON de jugadores para tests — devuelve un dataset pequeño y predecible
module.exports = {
  items: [
    {
      id: 1,
      rank: 1,
      overallRating: 91,
      firstName: 'Lionel',
      lastName: 'Messi',
      commonName: 'Messi',
      birthdate: '06/24/1987 12:00:00 AM',
      height: 169,
      weight: 67,
      skillMoves: 4,
      weakFootAbility: 3,
      preferredFoot: 1,
      leagueName: 'MLS',
      avatarUrl: 'https://example.com/messi.png',
      shieldUrl: 'https://example.com/shield.png',
      alternatePositions: [],
      playerAbilities: [],
      team: { id: 1, label: 'Inter Miami' },
      position: {
        id: '16',
        shortLabel: 'DCH',
        label: 'Delantero centro',
        positionType: { id: 'forward', name: 'Delantero' },
      },
      stats: {
        pac: { value: 85, diff: 0 },
        sho: { value: 92, diff: 0 },
        pas: { value: 91, diff: 0 },
        dri: { value: 95, diff: 0 },
        def: { value: 34, diff: 0 },
        phy: { value: 65, diff: 0 },
        acceleration: { value: 91, diff: 0 },
        agility: { value: 91, diff: 0 },
      },
    },
    {
      id: 2,
      rank: 2,
      overallRating: 90,
      firstName: 'Cristiano',
      lastName: 'Ronaldo',
      commonName: 'C. Ronaldo',
      birthdate: '02/05/1985 12:00:00 AM',
      height: 187,
      weight: 83,
      skillMoves: 5,
      weakFootAbility: 4,
      preferredFoot: 1,
      leagueName: 'Saudi Pro League',
      avatarUrl: 'https://example.com/cr7.png',
      shieldUrl: 'https://example.com/shield.png',
      alternatePositions: [],
      playerAbilities: [],
      team: { id: 2, label: 'Al Nassr' },
      position: {
        id: '16',
        shortLabel: 'DC',
        label: 'Delantero centro',
        positionType: { id: 'forward', name: 'Delantero' },
      },
      stats: {
        pac: { value: 87, diff: 0 },
        sho: { value: 93, diff: 0 },
        pas: { value: 81, diff: 0 },
        dri: { value: 88, diff: 0 },
        def: { value: 35, diff: 0 },
        phy: { value: 78, diff: 0 },
        acceleration: { value: 87, diff: 0 },
        agility: { value: 74, diff: 0 },
      },
    },
  ],
  totalItems: 2,
};
